### ISSUE TITLE
Help wanted: How did you generate the sidebar nav and bottom

### ISSUE THREAD

**Issue by ArjunDandagi** [iadvize/documentation#176]
Hi , 
The documentation site is amazing , i am thrilled that you have accomplised this using only writing the README files .

can you kindly let me know how you generated the sidebar and the navbar ,is this a custom coding separately on your servers.

I see that navigation.md is been used to do this. but i couldnt conclude how the site itself is generated. 

Thanks ,
Arjun

**Comment by sdemonti** [comment]
Hello, thanks you for you're feedback. We used [js-toc](https://tscanlin.github.io/tocbot) for the sidebar menu effect and rendering.
